#!/bin/bash
set -euf -o pipefail
out () { printf %s\\n "$*" ; }

out "Commands that may help brew fix itself:"
out "brew --config"
out "brew --prefix"
out "brew doctor"
out "brew update"
out "brew upgrade"
out "brew prune"
out "brew-fresh"
out "brew-group"
out "cd /usr/local/Library && git stash && git clean -d -f"
out "ls -ld \$(brew --prefix)"
out "ls -la \$(brew --prefix)"
out "cd \$(brew --prefix) && sudo chown $USER .git Library"
