#!/bin/bash
set -euf -o pipefail

##
# Brew is a MacOSX package manager.
#
# This script fetches fresh content from the the brew repository.
#
# This can be useful to repair a damaged brew installation.
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2016-01-10
##

cd $(brew --prefix)
git remote add origin https://github.com/mxcl/homebrew.git
git reset --hard FETCH_HEAD
git clean -df

out "Optionally run these:"
out "brew --config"
out "brew --prefix"
out "brew doctor"
out "ls -ld \$(brew --prefix)"
out "ls -la \$(brew --prefix)"
out "cd \$(brew --prefix) && sudo chown $USER .git Library"
