#!/bin/bash
set -euf -o pipefail

##
# Fetch fresh content from the the brew repository.
# This can be useful to repair a damaged brew installation.
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2016-01-10
##

cd $(brew --prefix)
git remote add origin https://github.com/mxcl/homebrew.git
git reset --hard FETCH_HEAD
git clean -df
